"""
daily_brief.py — Automated Pre-Market Brief → Telegram
========================================================
Run via cron at 8:00 AM ET (12:00 PM Dubai / 12:00 UTC):
  0 12 * * 1-5 cd /home/bala/dev/apps/agent-trader && PYTHONPATH=scripts .venv/bin/python scripts/tools/daily_brief.py

Generates a compact morning brief:
  - Index futures (SPY, QQQ direction from DuckDB)
  - Gap scan of all positions
  - Today's economic events (high/medium impact)
  - Earnings tonight for any watchlist ticker
  - Top 3 setups from scanner
"""

import sys
import json
import logging
import requests
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from scripts.session.scanner import scan, WATCHLIST
from scripts.feeds.econ_calendar import build_calendar

logger = logging.getLogger(__name__)

SECRETS = Path(__file__).parent.parent.parent / ".secrets" / "telegram.json"
POSITIONS_FILE = Path(__file__).parent.parent.parent / "data" / "positions.json"


def load_telegram_config():
    if not SECRETS.exists():
        return None, None
    creds = json.loads(SECRETS.read_text())
    return creds.get("bot_token"), creds.get("chat_id")


def send_telegram(text: str, bot_token: str, chat_id: str):
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    resp = requests.post(url, json={
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown",
        "disable_web_page_preview": True,
    }, timeout=10)
    return resp.ok


def build_brief() -> str:
    now = datetime.now(timezone.utc)
    lines = []
    lines.append(f"📋 *Pre-Market Brief* — {now.strftime('%a %b %d, %Y')}")
    lines.append("")

    # 1. Scanner results
    try:
        scan_data = scan()
        results = scan_data.get("results", [])

        # Index futures proxy (SPY, QQQ from scanner)
        for idx in ["SPY", "QQQ"]:
            r = next((x for x in results if x["ticker"] == idx), None)
            if r:
                emoji = "🟢" if r["gap_pct"] > 0 else "🔴" if r["gap_pct"] < 0 else "⚪"
                lines.append(f"{emoji} *{idx}*: {r['gap_pct']:+.2f}% @ ${r['price']:.2f}")
        lines.append("")

        # Position gaps
        positions = []
        if POSITIONS_FILE.exists():
            positions = json.loads(POSITIONS_FILE.read_text())
        pos_tickers = {p["ticker"] for p in positions}

        if pos_tickers:
            lines.append("*Portfolio Gaps:*")
            for r in results:
                if r["ticker"] in pos_tickers:
                    emoji = "🟢" if r["gap_pct"] > 0.3 else "🔴" if r["gap_pct"] < -0.3 else "⚪"
                    lines.append(f"  {emoji} {r['ticker']}: {r['gap_pct']:+.2f}% vol={r['vol_ratio']:.1f}x {r['setup']}")
            lines.append("")

        # Top 3 setups
        ideas = [r for r in results if r["setup"] in ("gap-and-go", "gap-fade") and r["ticker"] not in ("SPY", "QQQ")]
        if ideas:
            lines.append("*Top Setups:*")
            for r in ideas[:3]:
                lines.append(f"  {'🚀' if r['setup']=='gap-and-go' else '📉'} *{r['ticker']}*: {r['gap_pct']:+.2f}% vol={r['vol_ratio']:.1f}x ATR={r.get('atr_pct','?')}% [{r['sector']}]")
            lines.append("")

        # Sector rotation
        sectors = scan_data.get("sectors", {})
        if sectors:
            sorted_sectors = sorted(sectors.items(), key=lambda x: abs(x[1]["avg_gap"]), reverse=True)
            lines.append("*Sector Flow:*")
            for sec, s in sorted_sectors[:5]:
                emoji = "🟢" if s["avg_gap"] > 0 else "🔴" if s["avg_gap"] < 0 else "⚪"
                lines.append(f"  {emoji} {sec}: {s['avg_gap']:+.2f}% ({s['gappers_up']}↑ {s['gappers_down']}↓)")
            lines.append("")

    except Exception as e:
        lines.append(f"⚠️ Scanner error: {e}")
        lines.append("")

    # 2. Economic calendar
    try:
        cal = build_calendar(days=1)
        events = cal.get("events", [])
        high_med = [e for e in events if e.get("impact") in ("High", "Medium")]
        if high_med:
            lines.append("*Today's Events:*")
            for e in high_med[:8]:
                icon = "🔴" if e["impact"] == "High" else "🟡"
                lines.append(f"  {icon} {e.get('time','TBD')} — {e['event']}")
            lines.append("")
        warnings = cal.get("warnings", [])
        if warnings:
            for w in warnings[:3]:
                lines.append(f"⚠️ {w}")
            lines.append("")
    except Exception as e:
        lines.append(f"⚠️ Calendar error: {e}")

    lines.append("_Generated by TradeDesk_")
    return "\n".join(lines)


def main():
    logging.basicConfig(level=logging.WARNING)

    brief = build_brief()
    print(brief)

    bot_token, chat_id = load_telegram_config()
    if bot_token and chat_id:
        if send_telegram(brief, bot_token, chat_id):
            print("\n✅ Sent to Telegram")
        else:
            print("\n❌ Telegram send failed")
    else:
        print("\n⚠️ No Telegram config — printed only")


if __name__ == "__main__":
    main()
